In [1]:
import torch
x = torch.rand(5, 3)
x


tensor([[0.5817, 0.4885, 0.0288],
        [0.5743, 0.4441, 0.2625],
        [0.0095, 0.5958, 0.4656],
        [0.4680, 0.2675, 0.3072],
        [0.3802, 0.7142, 0.7141]])

In [24]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [25]:
x.shape

torch.Size([12])

In [26]:
x.numel()

12

In [27]:
X = x.reshape(3, 4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [28]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [29]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [30]:
torch.randn(3, 4)

tensor([[ 1.0077,  0.8557, -1.6261, -0.4107],
        [-1.9321,  0.6537, -0.5917,  0.6891],
        [-0.7890,  0.7789,  1.1144, -0.1195]])

In [31]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])



tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [34]:
x = torch.tensor([1, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y


(tensor([ 3,  4,  6, 10]),
 tensor([-1,  0,  2,  6]),
 tensor([ 2,  4,  8, 16]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]))

In [35]:
x ** y


tensor([ 1,  4, 16, 64])

In [36]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [37]:
x = torch.arange(12,dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [38]:
x = x.reshape(3, 4)
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [39]:
y = torch.tensor([[2.0, 1.0, 4.0, 3.0], [1.0, 2.0, 3.0, 4.0], [4.0, 3.0, 2.0, 1.0]])
y

tensor([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]])

In [40]:
torch.cat((x, y), dim=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])

In [41]:
torch.cat((x, y), dim=1)

tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])

In [43]:
x == y


tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [44]:
x.sum()

tensor(66.)

In [59]:
a = torch.arange(3).reshape((3, 1))
a

tensor([[0],
        [1],
        [2]])

In [60]:
a.reshape((3, 1))
a

tensor([[0],
        [1],
        [2]])

In [61]:
b = torch.arange(2).reshape((1, 2))
b

tensor([[0, 1]])

In [62]:
a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [63]:
x,x[-1]

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([ 8.,  9., 10., 11.]))

In [64]:
x,x[1:3]

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [65]:
x[1:2, :] = 12
x

tensor([[ 0.,  1.,  2.,  3.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

In [66]:
befor = id(y)
y = y+x
id(y) == befor

False

In [68]:
z = torch.zeros_like(y)

print('id(Z):', id(z)),z

id(Z): 1916583899232


(None,
 tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]))

In [69]:
z[:] = x + y
z,print('id(Z):', id(z))


id(Z): 1916583899232


(tensor([[ 2.,  3.,  8.,  9.],
         [25., 26., 27., 28.],
         [20., 21., 22., 23.]]),
 None)

In [70]:
a = x.numpy()
b = torch.tensor(a)
type(a), type(b)


(numpy.ndarray, torch.Tensor)

In [71]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)


(tensor([3.5000]), 3.5, 3.5, 3)

In [3]:
import os
os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n') # 列名
    f.write('NA,Pave,127500\n') # 每⾏表⽰⼀个数据样本
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

In [4]:
# 如果没有安装pandas，只需取消对以下行的注释来安装pandas
# !pip install pandas
import pandas as pd

data = pd.read_csv(data_file)
print(data)



   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000


In [7]:
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]
# inputs = inputs.fillna(inputs.mean())

# --- 修改点在这里 ---
# 使用 numeric_only=True，这样 mean() 只会计算 NumRooms 的均值，忽略 Alley
inputs = inputs.fillna(inputs.mean(numeric_only=True)) 

print(inputs)

   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN


In [8]:
inputs = pd.get_dummies(inputs, dummy_na=True)
print(inputs)

   NumRooms  Alley_Pave  Alley_nan
0       3.0        True      False
1       2.0       False       True
2       4.0       False       True
3       3.0       False       True


In [9]:
import torch

X = torch.tensor(inputs.to_numpy(dtype=float))
y = torch.tensor(outputs.to_numpy(dtype=float))
X, y

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500., 106000., 178100., 140000.], dtype=torch.float64))